spring:
  main:
    web-application-type: none
  jackson:
    default-property-inclusion: non_empty

exporter:
  scan-mode: JAR
  input-path: ~
  output-path: ./open-api.json
  include-filters: ~
  exclude-filters: ~
